### ISSUE TITLE
nucleus-dark-ui/index.less

### ISSUE THREAD

**Issue by uriberma** [ignism/nucleus-dark-ui#101]
Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

**Comment by ignism** [comment]
I think you may be running an older version of Nucleus
