### ISSUE TITLE
Change “Disable/Enable Package” button colors

### ISSUE THREAD

**Issue by matteodelabre** [ignism/nucleus-dark-ui#102]
Currently, in the package settings view, the “Disable” action is green and the “Enable” action is yellow. In my opinion, this feels a bit odd because the color does not match the text (“Enable” is a positive action and “Disable” is a negative one). Also, in the packages view, I’m not sure whether it’s useful to make the “Disable” button stand out by coloring it, because it does not require particular attention.

![“Enable” and “Disable” buttons example](https://cloud.githubusercontent.com/assets/1370040/24832209/d5fa8cd4-1caa-11e7-8f99-d4326e68a0ed.gif)

A solution would be to inherit parent color for the “Disable” action and use green for the “Enable” action.

**Comment by ignism** [comment]
Youre right, however removing the colors would remove the ability to quickly scan for disabled packages. I will look into this.

**Comment by matteodelabre** [comment]
What about only coloring the button if a package is disabled? It would still allow visual scanning of disabled packages.

**Comment by ignism** [comment]
i've changed the button from `color-success` to `color-info` to and gave the disabled packages title an extra orange tint. Will be updated in next patch. I;ve some other stuff ready for roll out.

**Comment by matteodelabre** [comment]
Thank you!
