### ISSUE TITLE
How do you make the Mac Window dark?

### ISSUE THREAD

**Issue by lacostenycoder** [ignism/nucleus-dark-ui#107]
Your screen shot shows the mac window Black but I can't seem to do that.
I'm on MacOS 10.11.6 and Atom 1.16.0
Thanks!

**Comment by ignism** [comment]
I think you refer to the title bar? It's in the Settings > Core, then all the way down under Title Bar.

**Comment by lacostenycoder** [comment]
@ignism yes I see it now, thanks.
