### ISSUE TITLE
Weird cmd+w behaviour in Atom beta

### ISSUE THREAD

**Issue by albireox** [ignism/nucleus-dark-ui#109]
I'm seeing a weird behaviour when using Atom beta. I cannot seem to write in any of the panes. Also, when I open a project the the top of the tree-view shows a tab-like button. When I try to close a tab by doing cmd+w the tree-view tab gets duplicated, but the tab I'm trying to close remains. See the attached screenshot.

I'm using Atom 1.17.0-beta2 with nucleus-dark-ui 0.11.15. This does not happen in Atom stable 1.16.0.

![screen shot 2017-04-17 at 22 06 52](https://cloud.githubusercontent.com/assets/568775/25105223/8d1abec2-23bb-11e7-9c8c-06cf72ee024e.png)

**Comment by ignism** [comment]
The tabs youre referring to above the tree-view is something new in the 1.17.0 release: Docks. Basicly they are panels you can hide, but use the tab system so you can drag tabs around to docks. It's really neat! I haven't been able to reproduce this bug as of yet, and I'm not sure whether it is something the theme does. Also. the treeview-tab is non-closeable, so something may be going on there.

**Comment by albireox** [comment]
You are right. After some painful experimentation it seems the problem is due to the package synced-sidebar, which anyway is deprecated by now. I think this can be closed.
