### ISSUE TITLE
use a semantic better close icon?

### ISSUE THREAD

**Issue by tinchoz49** [ignism/nucleus-dark-ui#16]
Hi @ignism !

I'm using your theme for the last month and it was great.
But i don't understand why you are using the github icon as a close icon, is just don't feel semantically right click in a cat to close things.

What do you think?

**Comment by ignism** [comment]
Hi man!
I am not sure what you mean. You mean the X in tabs and stuff? I am using that X because its the same as in OS X. But maybe I am wrong and you mean something else, or this doesn't work for you. If so, could you please send a little screenshot of the issue?

**Comment by tinchoz49** [comment]
Hi @ignism :) ! Yes i mean the X in tabs and stuff. Take a look this screenshot in linux:
![captura de pantalla de 2015-09-04 13 36 59](https://cloud.githubusercontent.com/assets/819446/9689136/4f79cbcc-530a-11e5-934b-a9bac93e39e9.png)

But for example the One Dark theme has a different icon more appropiate for a close button:
![captura de pantalla de 2015-09-04 13 37 19](https://cloud.githubusercontent.com/assets/819446/9689137/4f85e40c-530a-11e5-83d5-370cb6c8c630.png)

How it looks in your OS X?

And excuse my bad English!

**Comment by ignism** [comment]
Oh, I am glad you brought this up. I have no access to linux, so I can't test it there. It should look like the screenshot in the README, I will definitely fix this this weekend.
I'll also try to see if I can put it on the right side for linux and windows, and keep it on the left for OS X.

**Comment by tinchoz49** [comment]
Thanks!! :) glad to help!! I enjoy using your theme!

**Comment by ignism** [comment]
it's only there when you hover your mouse I guess?

**Comment by tinchoz49** [comment]
yes

**Comment by ignism** [comment]
Hey @tinchoz49, I've uploaded a patch. Would you be so kind to check it out and report back? If you could also provide a screenshot of how it looks.

**Comment by tinchoz49** [comment]
is working like a charm :+1: !

thanks! for the future here you have a linux tester if you need it!

**Comment by tinchoz49** [comment]
do i close the issue?

**Comment by ignism** [comment]
Thanks for your help, yeah I'll close it.

**Comment by MadcapJake** [comment]
This was my problem too! Glad it's fixed, this is definitely my favorite Atom theme! :+1:
