### ISSUE TITLE
Minor styling issues with imdone-atom package

### ISSUE THREAD

**Issue by onetrev** [ignism/nucleus-dark-ui#18]
Sorry, I know it would be a pain to support all the packages out there, but this one does seem to be picking up decent popularity after being a featured package on Atom.io. It's just a minor styling glitch I think, the background doesn't show between the cards. 

![untitled-1](https://cloud.githubusercontent.com/assets/597601/9695676/15aa14a6-5319-11e5-8655-7a1b9f5f8a52.png)

**Comment by ignism** [comment]
Updated in patch version 0.2.11
