### ISSUE TITLE
tree-view style problem

### ISSUE THREAD

**Issue by baurigae** [ignism/nucleus-dark-ui#19]
There's a problem with the way treeview directory names display (second picture is with this theme's tree-view style removed):

![tv](https://cloud.githubusercontent.com/assets/5447269/9699313/cc35c81c-53de-11e5-9705-5bb07c11057d.png)

Thanks for looking into it & thanks for the theme!

**Comment by ignism** [comment]
I think this is a font issue, but I am not sure. I want to fix this, but to be honest I don't know how to reproduce the problem. How do you open a project folder like that? If I am not mistaken you are working directly in the files online?

**Comment by baurigae** [comment]
I'm not sure what you mean - but it's just a repo directory that I have locally on my computer, that I sync with GitHub.
Anyway I tried different fonts, no change.
I have deduced this much so far: the bit in your tree-style.less that removes the directory icon (seen in the bottom scrot) messes up with the formatting (of the brackets in this case).

**Comment by ignism** [comment]
ok, let me have a look at it. Do you mind to test some code, if I put it here? Rather than me uploading a patch (which might not work).

**Comment by baurigae** [comment]
I'm fine with that :)

**Comment by ignism** [comment]
what happens if you comment out line 22, like so: 
`//display: none;`

on a side note: When I open a folder locally I just get the folder-name, not the `name.github.io [master]`, is this a linux thing? Or am I doing it wrong?

**Comment by baurigae** [comment]
1.
Now it displays properly (but shows the icon)
Like so:

[t](https://cloud.githubusercontent.com/assets/5447269/9741799/b68d0cde-565c-11e5-8d93-cd1bb3da1314.png)

.. which solves this issue for me - but if you want to test further to lose the icon as well, I'll help with that.

2. 
No idea as I run only Linux on this machine so can't test what it does on other OS's. I added my directory to the treeview via `file>add project folder` btw.
(Works fine with other themes, reason I thought I'd bother you :)

**Comment by baurigae** [comment]
1.
Now it displays properly (but shows the icon)
Like so:

![t](https://cloud.githubusercontent.com/assets/5447269/9741925/8b164b28-565d-11e5-81bb-709cc31de38d.png)

.. which solves this issue for me - but if you want to test further to lose the icon as well, I'll help with that.

2.
No idea as I run only Linux on this machine so can't test what it does on other OS's. I added my directory to the treeview via `file>add project folder` btw.
(Works fine with other themes, reason I thought I'd bother you :)

**Comment by ignism** [comment]
~~hmm, ok. Now, so it appears that `[` is a `:before`. maybe remove the comment again and change line 21 like this:~~
`21    &.icon:before {`
`22        display: none;`

EDIT: This is now implemented in patch 0.3.2, check if this works for you.

**Comment by baurigae** [comment]
Yup works fine, I updated as well. 
Thanks!
