### ISSUE TITLE
UI conflict with Clipboard Plus

### ISSUE THREAD

**Issue by onetrev** [ignism/nucleus-dark-ui#20]
Sorry found another package that has a bit on an issue with Nucleus Dark UI. The content in the [Clipboard Plus](https://atom.io/packages/clipboard-plus) modal is not readable.

![untitled-1](https://cloud.githubusercontent.com/assets/597601/9700331/8bb5ce3e-53b3-11e5-8810-be9c92b1470a.png)

PS, tried to use your donation link, but it the PayPal page shows up in Dutch and it doesn't let you change to Canada as the country.

**Comment by ignism** [comment]
Thanks for the feedback. I updated nucleus with a patch for the Atom-Runner issue, incidently it also helped clearing up Clipboard Plus. However I do think I still needs some styling so I leave the issue open for now. Thanks for pointing out PayPal acts up funny, let me check that.

**Comment by ignism** [comment]
Updated styles, along with others, in a version 0.3.0

**Comment by ignism** [comment]
On a side note: I just updated the link to the paypal donate form. Not asking for you to donate, just can you check if it's in English right now?

**Comment by onetrev** [comment]
Yes, it's English now! And it works...I tested it! :)  I think we all need to pitch in a bit more to support the work people do in the open source community.

**Comment by ignism** [comment]
Great! thanks a bunch man and I totally agree. In fact, maybe it's something github itself should make available.
