### ISSUE TITLE
atom-runner output text

### ISSUE THREAD

**Issue by MadcapJake** [ignism/nucleus-dark-ui#21]
[atom-runner](https://github.com/lsegal/atom-runner/)'s output text is too dark to be seen:

![screenshot from 2015-09-05 17-46-09](https://cloud.githubusercontent.com/assets/3377525/9701583/531a9292-53f6-11e5-9d10-fa856c7e99f9.png)

If the white background can be changed that'd be sweet too!  But I've noticed that changing the UI theme only seems to affect the text color (I think atom-runner needs to fix how they handle theming).

**Comment by ignism** [comment]
Fixed in patch version 0.2.10

**Comment by MadcapJake** [comment]
Thanks! :+1:
