### ISSUE TITLE
Increase contrast for selection region

### ISSUE THREAD

**Issue by denysbutenko** [ignism/nucleus-dark-ui#22]
I had some problems with contrast of selected region of the text.

UI Theme: **Nucleus Dark 0.2.15**
Syntax Theme: **Spacegray Eighties Dark 0.7.1**

Current version:
<img width="1552" alt="screenshot 2015-09-08 14 04 30" src="https://cloud.githubusercontent.com/assets/351613/9733351/173d1d14-5633-11e5-8537-6260a4689380.png">

Modified version:
<img width="1552" alt="screenshot 2015-09-08 14 09 50" src="https://cloud.githubusercontent.com/assets/351613/9733372/538d77e6-5633-11e5-8526-5464fb221f3c.png">

**Comment by ignism** [comment]
Hi, I can't find the syntax theme on atom. Is it still available? If so, can you link me to it? I don't have this issue with any of the syntax themes im using, unless they don't include a `syntax-variables.less` file.

**Comment by denysbutenko** [comment]
You're right.
Syntax theme was placed here: https://github.com/R1ZZU/spacegray-eighties-dark-syntax
I've installed https://atom.io/themes/base16-syntax and selection looks good.

<img width="1552" alt="screenshot 2015-09-08 15 58 55" src="https://cloud.githubusercontent.com/assets/351613/9735337/b7dc4fec-5642-11e5-807b-d7f934e69b74.png">
