### ISSUE TITLE
Line number gutter no longer transparent?

### ISSUE THREAD

**Issue by scwood** [ignism/nucleus-dark-ui#23]
Is the gutter having a background color and thick border intended? I don't see anything about it in the recent commits. I really like the transparent gutter.

This happened after updating to 0.3.1

![screen shot 2015-09-08 at 4 45 26 pm](https://cloud.githubusercontent.com/assets/9126138/9749306/0a114b54-5649-11e5-9efc-2083e1309013.png)

**Comment by ignism** [comment]
I'm having issues with overall overriding of styles of the text editor. Looking into this now.

**Comment by ignism** [comment]
Apparently the Atom Beautify package adds an extra space in front of ::shadow, which made all Shadow DOM styles fail. It's fixed in patch 0.3.2
