### ISSUE TITLE
font size when close log

### ISSUE THREAD

**Issue by dmaglio** [ignism/nucleus-dark-ui#25]
I use remote-sync to upload file in my server, if i try to minimize the log the font size become very large...
is it an issue of the theme or the remote-sync package?

**Comment by ignism** [comment]
Not familiar with the package, yet. I will look into this now and see if I can reproduce it and fix it.

**Comment by dmaglio** [comment]
![schermata da 2015-09-14 16-25-57](https://cloud.githubusercontent.com/assets/446573/9852214/53774146-5afd-11e5-9b24-60ab026bbd04.png)

this is an example

**Comment by ignism** [comment]
Pushed a new patch, should work now!

**Comment by dmaglio** [comment]
perfect, work correctly :+1:

**Comment by ignism** [comment]
Added some more styling for the configure panel.
