### ISSUE TITLE
Notification close button

### ISSUE THREAD

**Issue by MadcapJake** [ignism/nucleus-dark-ui#26]
I was working through a few [tweaks](https://gist.github.com/MadcapJake/de27004e3e44bf3f7351) to colors to make Atom fit better with [arc-theme](https://github.com/horst3180/Arc-theme) and I noticed that notifications with close buttons use the github icon instead of an `x`.  Seems like it's related to a previous bug with the tab close button (#16).

![screenshot from 2015-09-15 10-39-33](https://cloud.githubusercontent.com/assets/3377525/9881559/28d38474-5b96-11e5-9886-2d2ee182bb1c.png)

**Comment by ignism** [comment]
fixed in patch 0.4.4
