### ISSUE TITLE
"Close All" button for notifications

### ISSUE THREAD

**Issue by MadcapJake** [ignism/nucleus-dark-ui#27]
Another bug I found in the same picture from #26 is the `Close All` button:

![screenshot from 2015-09-15 10-39-33](https://cloud.githubusercontent.com/assets/3377525/9881559/28d38474-5b96-11e5-9886-2d2ee182bb1c.png)

**Comment by ignism** [comment]
I will look into it, mind if I ask what package you are using to simulate those errors? (specifically the toolbar in the bottom)

**Comment by ignism** [comment]
fixed in patch 0.4.4

**Comment by MadcapJake** [comment]
In Atom's Dev Mode, the Atom Notifications package provides that panel via the command `notifications:toggle-dev-panel`.

Thanks for the quick fix! :+1:

**Comment by ignism** [comment]
Thanks you, and you're welcome!
