### ISSUE TITLE
Failed to activate the nucleus-dark-ui theme

### ISSUE THREAD

**Issue by nimrc** [ignism/nucleus-dark-ui#29]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.15
**System**: Unknown Windows Version
**Thrown From**: [nucleus-dark-ui](https://github.com/ignism/nucleus-dark-ui) package, v0.4.5
### Stack Trace

Failed to activate the nucleus-dark-ui theme

```
At Recursive variable definition for @syntax-color-added in C:\Users\wangtansheng\.atom\packages\nucleus-dark-ui\index.less:17:157

LessError: Recursive variable definition for @syntax-color-added
  at C:\Users\wangtansheng\.atom\packages\nucleus-dark-ui\index.less:17:157
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "spacegray-dark-neue-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
emmet, v2.3.12
linter, v1.6.0
linter-php, v1.0.3
minimap, v4.13.3
minimap-git-diff, v4.1.8
spacegray-dark-neue-syntax, v1.3.0
symfony-snippets, v0.3.0
web-browser, v1.5.0

# Dev
No dev packages
```

**Comment by ignism** [comment]
The problem is this specific syntax theme uses the `@text-color-*` variables, which are actually UI theme variables, hence the recursive loop.

**Comment by nomoon** [comment]
@ignism This appears to be occurring on 1.17-beta2 even with the default syntax theme and an empty user stylesheet.

```
Error compiling Less stylesheet: [omitted]/.atom/packages/nucleus-dark-ui/index.less
Line number: 1
Missing closing ')'
```

```
Failed to activate the nucleus-dark-ui theme
Missing closing ')' in [omitted]/.atom/packages/nucleus-dark-ui/styles/overlays.less:1:10
```

**Comment by ignism** [comment]
I did experience it too, but it makes no sense, there are no missing ')', and there is none in overlays.less on line nr 1 place 10.

**Comment by albireox** [comment]
Getting the same error once I updated to the latest beta (1.17.0-beta2) on a Mac.

**Comment by ignism** [comment]
Should be fine now

**Comment by objectkit** [comment]
Hi -just downloaded the latest update (12.2) and same issue I'm afraid! Atom 1.17 is a bit of a balls up. Downgraded to Atom 1.16. This error still popping up?

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.0 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.5
**Thrown From**: [nucleus-dark-ui](https://github.com/ignism/nucleus-dark-ui) package 0.12.2


### Stack Trace

Failed to activate the nucleus-dark-ui theme

```
At Unrecognised input in /Users/davidfoley/.atom/packages/nucleus-dark-ui/styles/atom.less:120:24

LessError: Unrecognised input
  at /packages/nucleus-dark-ui/styles/atom.less:120:24
```

### Commands

```
     -0:05.9.0 tree-view:show (atom-workspace.workspace.scrollbars-visible-when-scrolling)
```

### Non-Core Packages

```
atom-beautify 0.29.24 
atom-live-server 2.1.2 
autocomplete-js-import 1.4.0 
browser-plus 0.0.87 
busy-signal 1.4.1 
Coffeefilter 0.2.0 
color-picker 2.2.5 
dash 1.7.1 
docblockr 0.9.4 
duotone-dark-desert-syntax 0.1.3 
duotone-snow 2.2.0 
emmet 2.4.3 
esformatter 2.2.1 
expose 0.14.0 
file-icons 2.1.5 
filesize 3.0.0 
focus-dark 1.2.0 
focus-light 1.2.0 
git-time-machine 1.5.9 
grayscale-syntax 0.1.0 
gruvbox-plus-syntax 1.3.1 
import-sf-mono 1.0.1 
intentions 1.1.2 
language-swift 0.5.0 
linter 2.1.4 
linter-coffeelint 1.2.1 
linter-ui-default 1.5.0 
local-history 4.1.1 
Lux-Syntax 2.0.0 
minimap 4.28.2 
minimap-bookmarks 0.4.2 
minimap-find-and-replace 4.5.2 
native-ui 0.20.6 
nucleus-dark-ui 0.12.2 
open-in-browser 0.5.0 
package-sync 1.1.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.0 
project-manager 3.3.4 
sunset 1.1.1 
swift-debugger 0.1.2 
todo-show 1.11.0 
vector-syntax 0.3.0 
visual-studio-code 0.4.0 
Writer 0.1.0 
```

**Comment by sirschuyler** [comment]
Have the same issue as @objectkit

**Comment by alex35mil** [comment]
Same here.

**Comment by jalendport** [comment]
same issue as @objectkit with Atom 1.1.17 and the newest version of Nucleus-Dark.

**Comment by jhliberty** [comment]
Same issue

**Comment by ignism** [comment]
Pushed a quick patch, with 0.12.3 all your problems should be gone again :)

**Comment by jalendport** [comment]
@ignism all fixed. thanks!

**Comment by objectkit** [comment]
Nice one! Thanks 👍
