### ISSUE TITLE
Long filename

### ISSUE THREAD

**Issue by juan-manuel-alberro** [ignism/nucleus-dark-ui#32]
Hello!

There's a bug when you create a new file and the path or the filename is quite long, the name appears in a new line like this

![image](https://cloud.githubusercontent.com/assets/7114488/10099406/b2eb72cc-635f-11e5-8724-19a74f836a0f.png)

Regards!

**Comment by ignism** [comment]
Hi there, what version are you running (both atom and my theme) and which OS. Since I just solved this issue last week.

**Comment by juan-manuel-alberro** [comment]
Hi @ignism! I'm using a Macbook with the latest version of Atom and your theme.
Regards!

**Comment by ignism** [comment]
Can you verify if it really is the latest version of my theme? since in a recent update I created the overlay bigger than how it looks like on your screenshot.
