### ISSUE TITLE
Invisible last line in editor

### ISSUE THREAD

**Issue by moeriki** [ignism/nucleus-dark-ui#33]
Dears,

Not sure if this would be an issue with the theme or perhaps another package.

The last line in my editor is not visible. As you can see in the screenshot, there is an invisible last line. You can see a few pixels of the cursor (white) and the highlighted line.

![image](https://cloud.githubusercontent.com/assets/38758/10164859/4c69c57a-66bc-11e5-897f-59da9842f054.png)

**Comment by ignism** [comment]
will look into this, however I did not run into this myself. Will try to recreate this.

**Comment by ignism** [comment]
I'm sorry, it appears it is not my theme. To make sure of it, I did a clean install with only one added package (the theme itself).
