### ISSUE TITLE
Notifications Over Tabs

### ISSUE THREAD

**Issue by MattTuttle** [ignism/nucleus-dark-ui#34]
At the moment Atom notifications show up over the tabs which makes it difficult to change tabs for a few seconds. I'm using the Haxe plugin for building a project as you can see below.

![screen shot 2015-10-01 at 11 26 22 am](https://cloud.githubusercontent.com/assets/620357/10226853/939b74ec-682f-11e5-941e-ebfdab5565e5.png)

I'm not sure what the best solution is but what seems to help in my case is to lower the notifications by 30 pixels. This is in my styles.css but I'm guessing other people may have the same issue and not know about custom styles.

``` css
atom-notifications {
    top: 30px;
}
```

Thanks for the great theme!

**Comment by ignism** [comment]
fixed in version 0.5.12
