### ISSUE TITLE
Gitignore `npm-debug.log` (or untrack)

### ISSUE THREAD

**Issue by blakeembrey** [ignism/nucleus-dark-ui#36]
I wanted to find out what had changed recently, but all I found was that the last three releases included changing a file that shouldn't even be checked in and all the "repatch" commits was someone trying to fix the mistake.

**Comment by ignism** [comment]
Yeah, I messed up with authorization. What happend was everytime I wanted to apm publish, it failed. however, it changed version number. wanted to "re-patch" and change the version number but that screwed up apm again.. and back and forth. Oh well, lesson learned. thanks for the tip.
