### ISSUE TITLE
The Preferred Line Length indicator and the panes separator are too similar

### ISSUE THREAD

**Issue by pheisiph** [ignism/nucleus-dark-ui#39]
Using [Solarized Dark Syntax](https://atom.io/themes/solarized-dark-syntax) the 80-character-line-length-indicator and the line that separates panes are identical. Could they be a bit different to avoid occasional confusion? 

![screen shot 2015-10-20 at 10 48 07](https://cloud.githubusercontent.com/assets/537743/10602512/0f418a76-7719-11e5-90cb-e1146796e759.png)

**Comment by ignism** [comment]
Yes, actually I'm already fiddling around with it. because I don't like it the guides are dissapearing when selecting blocks of text.

**Comment by pheisiph** [comment]
Lovely, thank you!
