### ISSUE TITLE
Text does not fit into new file (modal overlay)

### ISSUE THREAD

**Issue by bitIO** [ignism/nucleus-dark-ui#4]
When creating a new file, if the path is a bit long (i.e. two folders), the name of the new file may end up in two lines, thus, the final part of the new file cannot be seen.

**Comment by ignism** [comment]
can you be more specific? I tried to reproduce this bug, but for me if I am typing in the New File modal, it will scroll for me so only the beginning of the path cannot be seen.

**Comment by bitIO** [comment]
Sure. Here you're.
![](https://dl.dropboxusercontent.com/u/596382/screenshot.png)
I think modifying overlays.less would fix it but not sure how (I've tried changing the font size but it's not enough since the cursor then is displaced).

**Comment by ignism** [comment]
This is strange, I can't reproduce it. The overlay will scroll if I start typing out form the start, but it will start at the end of the line when I am in a deeper folder structure, see below:
![makingagif](https://cloud.githubusercontent.com/assets/2485645/9196284/157e4be8-402a-11e5-93c8-f63785de2050.gif)

**Comment by bitIO** [comment]
Weird. Maybe it has to do something with a custom style or another extension that is modifying the overlays style. I'm going to have a look and I'll keep you posted.

**Comment by bitIO** [comment]
Just for the record, which tree-view are you using? The default one [https://github.com/atom/tree-view](https://github.com/atom/tree-view)? I've seen (this post)[https://discuss.atom.io/t/scroll-atom-text-editor-to-end-of-long-text/18771] which suggests that "dialog expands vertically when the text doesn't fit horizontally."

**Comment by bitIO** [comment]
Found it! The one to _blame_ is soft wrap! You can see the issue here https://github.com/atom/tree-view/issues/473#issuecomment-113733850
I think this issue can be closed!

**Comment by ignism** [comment]
Thanks for your effort BitIO
