### ISSUE TITLE
Non-filling tabs

### ISSUE THREAD

**Issue by palango** [ignism/nucleus-dark-ui#40]
Have you thought about make the tabs non-filling or providing an option for that?

**Comment by ignism** [comment]
Hi, what do you mean with, non-filling?

**Comment by palango** [comment]
I mean that the tabs always take the full available width. If I have just one tab, then it takes 100%. When there are two, then each takes 50%.
I think it would be nice if each tab would just take the width it needs.

**Comment by ignism** [comment]
I modeled them after the tabs in OS X. I might include an option to switch it though.
