### ISSUE TITLE
Overides Github Markdown Preview colors

### ISSUE THREAD

**Issue by ghost** [ignism/nucleus-dark-ui#43]
When using Github.com styling, the headings in GFM preview are being set to the font color declared in by nucleus-dark-ui, and not the by the stylings of markdown-preview.

**Comment by ignism** [comment]
Can you give me an example of markdown syntax you use to color a font?

**Comment by ghost** [comment]
I'm using stock Atom, with `nucleus-dark-ui` and stock `markdown-preview` with "Use Github.com style" checked in the Settings. Upon `ctrl-shift-m` the markdown preview headings look like this:

![withnuc](https://cloud.githubusercontent.com/assets/9103375/11025741/54954474-8654-11e5-9f3a-c8f7cd194902.png)

When I switch to One Dark UI, the markdown preview headings look like this:

![withoutnuc](https://cloud.githubusercontent.com/assets/9103375/11025749/69090ecc-8654-11e5-9db1-575fc53693bd.png)

**Comment by ignism** [comment]
fixed as of patch 0.6.8

**Comment by ghost** [comment]
Thank you. :+1: works well
