### ISSUE TITLE
Feature Request: Custom or Larger Theme Text Sizes

### ISSUE THREAD

**Issue by objectkit** [ignism/nucleus-dark-ui#44]
Great theme! I'd love to be able to make Atoms text larger for readabilities sake though (e.g. settings view). I did quickly try and modify the packages styles/atom.less by creating a @customFontSize variable of 13px and then assigning it for each font-size attribute with 11px in that file, but didn't have much success as I'm not used to Atom theming. Any plans on enlarging the font size or any guidance on how I could customise this myself? I understand it may not be everyones cup of tea to make the text larger in a release. Thanks

**Comment by ignism** [comment]
Hi! Thanks for the feedback. You got a good point, I should consider this. I am thinking about implementing this, along with a feature that sets tabs to something more familiar to windows users. However, this needs some testing. Especially font-size might mess up the overal mark-up. like some buttons may become unreadable.
Maybe a quick fix for now, try adding `!important` just before the `;` of the styles you are changing. This enforces the style.

**Comment by objectkit** [comment]
No problem - apologies for the day getting back to you! I didn't get the chance to edit the themes less locally, but a number of updates later, and on a different machine, and it seems that you must have implemented this! IDE text is now bigger and looking good... unless I FUBAR'ed the less in passing and it just happenchanced to work out by itself?
