### ISSUE TITLE
Using Roboto as a fallback for non-OS X devices

### ISSUE THREAD

**Issue by Unpaid8503** [ignism/nucleus-dark-ui#47]
I really loved this theme when I saw the screenshots, but I got disappointed when it didn't look like anything in the screenshots at all in my Windows machine, because the theme uses Apple's San Francisco and Helvetica, which isn't available on Windows and Linux.

Roboto could be used as a fallback for for these OSes so it matches the look in OS X. It's also popular, free and easy to install.

Here's a preview of Atom with Nucleus Dark UI without Roboto:
![preview of Atom with Nucleus Dark UI without Roboto](http://i.imgur.com/0PAQhVc.png)

After changing of ui-variables.less to fallback into Roboto (Roboto Light for medium so it looks light overall) :
![preview of Atom with Nucleus Dark UI without Roboto](http://i.imgur.com/YLpaiW0.png)

**Comment by ignism** [comment]
I have no access to windows at the moment, your screenshots look good. Is roboto standard in windows, or do I need to import or include it?

**Comment by Unpaid8503** [comment]
@ignism Roboto is not standard in Windows, but it's available as a webfont in Google Fonts: https://www.google.com/fonts/specimen/Roboto

The license allows you to include it with the theme as well, so it can be available offline

**Comment by onetrev** [comment]
Sorry to add on to this closed item but am I the only one thinking this new Roboto font setup is a bit too thin?

![snip_20151116105222](https://cloud.githubusercontent.com/assets/597601/11191487/61454794-8c50-11e5-9aa5-1e61b556c2ce.png)

It is especially noticeable in the footer...

![snip_20151116114909](https://cloud.githubusercontent.com/assets/597601/11192839/2281cf16-8c58-11e5-86a6-a5cff05551b0.png)

**Comment by ignism** [comment]
you're right. This sucks. could you try and check something for me, since I don't have access to windows? in the `ui-variables.less` file, one the 2nd line, that imports Roboto. What happens if you remove the lighter version (300)?

**Comment by onetrev** [comment]
Can do. I tried it out. Seems the same to me. Is it a problem though I have all versions of Roboto installed locally already?

**Comment by ignism** [comment]
yeah, the import function doesnt even seem to work on my end. I think I just remove it alltogether.

**Comment by chriskrycho** [comment]
Suggestion: instead of using Roboto on Windows, use the Segoe UI font, which is bundled with Windows since Vista, and is Microsoft's recommendation for native UI elements.

**Comment by ghost** [comment]
On Linux instead of Roboto try using Liberation Sans. It's a good replacement for Helvetica. Or if you want a wider font use Noto Sans, which is similar to Segoe UI.

**Comment by ignism** [comment]
I referred to Noto Sans
