### ISSUE TITLE
Fold indicators are hidden when combined with Atom Fusion Dark

### ISSUE THREAD

**Issue by benmccormick** [ignism/nucleus-dark-ui#48]
I originally opened this in the Atom-Fusion-Dark repository, but it seems to be a conflict issue since both themes seem to work fine independently of each other: https://github.com/MaxGraey/atom-dark-fusion-syntax/issues/4

When I combine this ui theme with the AFD syntax theme, I'm unable to see the fold arrows.  I'd like to make this work, any suggestions?

With Nucleus Dark Theme

<img width="378" alt="dashboard_less_-__users_ben_code_windsor_wcui_dev_src_wcui_-_atom" src="https://cloud.githubusercontent.com/assets/1899941/11218406/7471897a-8d1a-11e5-8d4c-6627789c1b2d.png">

With Atom Dark theme

<img width="370" alt="dashboard_less_-__users_ben_code_windsor_wcui_dev_src_wcui_-_atom" src="https://cloud.githubusercontent.com/assets/1899941/11218688/0edf8c18-8d1c-11e5-8f8e-8ecd37a333aa.png">

**Comment by ignism** [comment]
hmm, it appears the gutter is too small for the fold indicators to be visible. It's late for me now, but I will definitely fix this later.

**Comment by ignism** [comment]
Heh, couldn't stand taking a quick look. I fixed it, should be ok for you now with patch 0.6.12

**Comment by benmccormick** [comment]
@ignism thanks so much!  For both the amazing response time and for the great work on the theme in general.  One of my favorite parts of using Atom has been the look and feel, a big part of which is your theme.

**Comment by benmccormick** [comment]
@ignism also confirmed this seems to be all better now.  Thanks again!
