### ISSUE TITLE
Syntax used in a screenshot

### ISSUE THREAD

**Issue by phnah** [ignism/nucleus-dark-ui#49]
![687474703a2f2f692e696d6775722e636f6d2f74436a5a4353562e706e67](https://cloud.githubusercontent.com/assets/778442/11289281/385b293e-8f7f-11e5-8da8-31429ba96243.png)

What is the syntax used in this screenshot? Thank you :)

**Comment by doabit** [comment]
@hanhpho  https://atom.io/themes/atom-dark-fusion-syntax

**Comment by guhelo** [comment]
Ah, thanks :)
