### ISSUE TITLE
Issues with show/hide label on tree view

### ISSUE THREAD

**Issue by YarnSphere** [ignism/nucleus-dark-ui#51]
Hi! Awesome work on the theme! I've found two issues with the show/hide labels on the tree view that you might want to look into.

This happens with long file names that cause a horizontal scroll bar to appear on the tree view:
![show](https://cloud.githubusercontent.com/assets/8314616/11527512/5deb40d6-98d9-11e5-89a9-8f6e2e08de48.png)
![hide](https://cloud.githubusercontent.com/assets/8314616/11527515/623a5dca-98d9-11e5-80e9-63149f6dec15.png)

And when the project folder's name is long:
![long title](https://cloud.githubusercontent.com/assets/8314616/11529550/b88e9d74-98e5-11e5-9bb9-28c46d76265d.png)

A way to solve this last issue would be to add a background to the tooltip (with a proper `padding`, etc.). The first one I'm not so sure how to solve (maybe using the usual arrow before the name instead of the tooltip would be better, although I do like the tooltip).

Please keep up the good work! :smile:

**Comment by YarnSphere** [comment]
Another issue, a bit harder to reproduce, but might also be related with the tooltips (look at the vertical scrollbar, it's glitched):
![weird](https://cloud.githubusercontent.com/assets/8314616/11530609/ddbaba8a-98ed-11e5-9c49-86d997129d7d.png)

This happens when you have enough files to show the vertical scroll bar and the horizontal scroll bar is also showing. Then simply mouse over and out of the project folder (causing the tooltip to appear/disappear). The vertical scrollbar of the tree view has a weird behaviour when the animation of the tooltip is occurring.

**Comment by YarnSphere** [comment]
Sorry, I pressed "close and comment" by mistake.

**Comment by ignism** [comment]
Thanks for the feedback. I'm looking into the first one. the second one however I can't reproduce. It might have to do with the OS, are you on OS X too?

**Comment by ignism** [comment]
I've uploaded a patch for the label issues.
But like I said, have not been able to reproduce the scrollbar issues yet.

**Comment by YarnSphere** [comment]
No, I'm not on OS X, I'm using Arch Linux.
I can't seem to reproduce it anymore, so the patches seem to have worked. :smile:

However, now the background of the selected folders/files (or when hovering the project folder) looks bad when you scroll right in the tree view (by bad I mean that it appears cropped).
