### ISSUE TITLE
Script Result Panel visual discrepancies

### ISSUE THREAD

**Issue by amucinom** [ignism/nucleus-dark-ui#52]
Awesome job on the theme, I really like it! :smile: 
I have one think that kind of looks off with the theme. I have this package, [script](https://github.com/rgbkrk/atom-script), that displays a panel of results after a script has been run. Currently, after being run with the theme, it looks like this: 
<img width="1273" alt="second" src="https://cloud.githubusercontent.com/assets/4065569/11862043/81b292e2-a443-11e5-870c-6e9573bcac2e.png">
I went in and edited some stuff using the Developer tools, and got it looking like this: 
<img width="1260" alt="first" src="https://cloud.githubusercontent.com/assets/4065569/11862051/9395858c-a443-11e5-9ec5-05306408d2c7.png">
I tried to replicate it by editing my stylesheet, but those changed take effect in other themes as well, making the other themes break in this panel, since I'm changing it globally. Hopefully it can be worked out so everything looks streamlined!

Thanks!

**Comment by ignism** [comment]
Haven't used script myself, but looks interesting! let me install it and try to make a fix around it.

**Comment by ignism** [comment]
Uploaded a patch, 0.7.3. See if this works for you.

**Comment by amucinom** [comment]
It does! Thank you very much, keep up the awesome work! :smile:
