### ISSUE TITLE
Styles in modals

### ISSUE THREAD

**Issue by alex35mil** [ignism/nucleus-dark-ui#53]
Hi! I found a few style issues with modals, one is pretty annoying when I try to create new folders/files in deep locations:

![screen_shot_2015-12-23](https://cloud.githubusercontent.com/assets/4244251/11981538/a85eca48-a9b4-11e5-9283-8d08349d753c.jpg)

**Comment by ignism** [comment]
What modal is this? Is it a custom package?

**Comment by alex35mil** [comment]
@ignism Yep, it's https://github.com/Osmose/advanced-open-file

In fuzzy finder it looks like this:

<img width="711" alt="screen shot 2016-01-21 at 14 55 34" src="https://cloud.githubusercontent.com/assets/4244251/12479904/54e446b6-c04f-11e5-8709-13033fa220a6.png">

All chars are visible, but there is no padding on the right. I don't think it's an issue with fuzzy finder itself (since nobody enters such long names there), but it might be related to issue in custom packages (like `advanced-open-file`).

**Comment by ignism** [comment]
Will look into this, I put it on my priority list. Sorry for the late reply, I started a new job in January and time is limited for me now.

**Comment by alex35mil** [comment]
NP, thanks for the awesome UI! :+1:

**Comment by ignism** [comment]
Finally fixed this nasty little bug as of version 0.7.17, the problem was the ::before content got in the way. giving it some space with padding did the trick. I still need to fix the non-critical stuff though so I leave it open.

**Comment by alex35mil** [comment]
Just updated theme and this bug is gone. Thanks a bunch! Closing this.
