### ISSUE TITLE
Problems with horizontal scrolling in tree-view

### ISSUE THREAD

**Issue by albireox** [ignism/nucleus-dark-ui#56]
When working on a project, if I need to scroll horizontally in tree-vew I get an ugly effect. See screenshot attached. I'm not seeing this effect with other themes, so I assume it's Nucleus-related. 

My system is Mac OSX 10.11.3 with Atom 1.6.0-beta4 (also tried it in the stable version with the same result).

![screen shot 2016-02-19 at 11 33 51](https://cloud.githubusercontent.com/assets/568775/13186815/ca1d3280-d6fc-11e5-88e8-7c302eea083b.png)

**Comment by ignism** [comment]
Ugh, that hurts my eyes...
I tried to reproduce it, but I don't have this problem. I did notice a new problem though, which is the way it highlights selections. I'll try to solve this by having a look at how Atom One Dark is doing the tree-view and rebuilding it from there. Hopefully this solves your problem as well.

**Comment by albireox** [comment]
Not sure if this helps, but this problem only seems to happen when you have a tab with a file open. If you open the settings tab, you can scroll without any artifact appearing.

**Comment by npatmaja** [comment]
I also have the same problem as described by @albireox, the horizontal scroll kind of broken when I have a file (or more) opened. I'm using atom 1.5.4 (stable version)

![nucleus-scrollbar-error](https://cloud.githubusercontent.com/assets/967979/13623567/24b1f58c-e5da-11e5-9b89-34d5d6f555f7.png)

**Comment by ignism** [comment]
should be fixed as of 0.7.11, let me know.

**Comment by albireox** [comment]
Seems to be fixed for me. Thanks!

**Comment by npatmaja** [comment]
It's fixed after updating. Thanks! :+1:
