### ISSUE TITLE
Small icon buttons look odd

### ISSUE THREAD

**Issue by trepidacious** [ignism/nucleus-dark-ui#59]
This is very minor, but since I really like everything else about the theme it seems worth mentioning. The very small buttons used in terminal-plus look odd with a border, since the icons get close to the edge of the button:

<img width="1738" alt="screen shot 2016-04-03 at 20 04 08" src="https://cloud.githubusercontent.com/assets/172154/14234292/87f47816-f9d7-11e5-83fe-6cb626deab39.png">

This looks better in some other themes that just have a slightly different coloured background for buttons, rather than a high contrast border. I guess this is also possibly a problem with terminal-plus - if the icons didn't get so close to the edge of the button, and were centered better, it would probably look fine.

**Comment by ignism** [comment]
streamlined since patch 0.7.18
