### ISSUE TITLE
Cannot change highlight line color

### ISSUE THREAD

**Issue by gyzerok** [ignism/nucleus-dark-ui#61]
With your theme I cannot do this because of `!important`

**Comment by edhv** [comment]
yes, I've did way too many dirty `!important` tricks. I need to clean this up.
Culd you specify what exactly  you tried to change?

**Comment by ignism** [comment]
yes, I've did way too many dirty !important tricks. I need to clean this up.
Culd you specify what exactly you tried to change?

**Comment by ignism** [comment]
Finally came around to remove all that.
