### ISSUE TITLE
Treeview font-size

### ISSUE THREAD

**Issue by sachq** [ignism/nucleus-dark-ui#63]
I'm unable to change the _font-size_ of the _treeview_

```
// .atom/style.less

@font-size: 10px;
.tree-view {
   font-size: @font-size;
}
```

<img width="258" alt="screen shot 2016-05-06 at 11 47 53" src="https://cloud.githubusercontent.com/assets/4220346/15065762/6fc8cd56-1380-11e6-908c-0f5efda76f2a.png">

**Comment by ignism** [comment]
try this

```
@font-size: 10px;
.tree-view, .list-item {
   font-size: @font-size;
}
```

**Comment by sachq** [comment]
Font size is reducing only when i hover on the items in the tree.

**Comment by ignism** [comment]
```
@font-size: 10px;
.tree-view, .list-item {
   font-size: @font-size !important;
}
```
