### ISSUE TITLE
Embedded atom editor is hiding content

### ISSUE THREAD

**Issue by keathley** [ignism/nucleus-dark-ui#64]
I ran into this issue with the atom-elixir package. There is an expanded view that allows you to view quoted and expanded code snippets like so:

(That screenshot is using the one dark)
![screenshot 2016-05-13 10 12 08](https://cloud.githubusercontent.com/assets/1642095/15251178/2837dd44-18f6-11e6-88c4-11a40ef62713.png)

However with nucleus the code blocks aren't expanded to the full height of the code:

![screenshot 2016-05-13 10 12 20](https://cloud.githubusercontent.com/assets/1642095/15251261/8758c98c-18f6-11e6-926c-577916fb6239.png)

I've tried looking through the inspector to see if I can figure out whats going on but I haven't seen anything obvious. I'm wondering if this is an issue with Nucleus or potentially an issue with how theses editors are implemented in atom-elixir.

**Comment by edhv** [comment]
Nice find, I'm not familiar with the package yet. I will look into this right away.

**Comment by keathley** [comment]
Awesome thanks!
