### ISSUE TITLE
Merge Conflicts Package - Invisible headers/footers

### ISSUE THREAD

**Issue by McAllaster** [ignism/nucleus-dark-ui#67]
I am seeing odd behavior in nucleus-dark-ui regarding the package [merge-conflicts](https://atom.io/packages/merge-conflicts), where the header/footer of a merge conflict does not show correctly.

one-dark-ui (desired functionality):
![screen shot 2016-06-14 at 11 01 14 am](https://cloud.githubusercontent.com/assets/5580190/16047803/948f9a26-321f-11e6-96be-451b2192829b.png)
![screen shot 2016-06-14 at 11 01 24 am](https://cloud.githubusercontent.com/assets/5580190/16047806/96981096-321f-11e6-8511-803653b7809a.png)
nucleus-dark-ui (undesired functionality):
![screen shot 2016-06-14 at 10 59 16 am](https://cloud.githubusercontent.com/assets/5580190/16047794/8f50bf0e-321f-11e6-8d33-1daeb2e6ec3f.png)
![screen shot 2016-06-14 at 10 59 51 am](https://cloud.githubusercontent.com/assets/5580190/16047799/911d2c96-321f-11e6-9904-2b9a8b0369ef.png)

As you can see, for some reason the header/footer is not displaying the correctly styled line, but instead displays the text that would otherwise be there from a manual merge syntax alongside the header/footer text from the merge-conflicts package.

This is really the only problem I have run into when using nucleus-dark-ui, and I love it a lot. However, I want to keep the productivity gains of having a marge conflict resolver inside of atom.

**Comment by ignism** [comment]
oof! that is really a nasty bug. I'm on it.
