### ISSUE TITLE
Can you use relative font-size?

### ISSUE THREAD

**Issue by zhaocai** [ignism/nucleus-dark-ui#69]
Fixed `px` size does not work with different settings.
## Example

``` CoffeeScript
.inset-panel .panel-heading,
    .panel-heading {
      .text(heading);
      font-size: 24px;
      border-radius: 0;
```

**Comment by ignism** [comment]
Hey! could you elaborate where this is a problem?

**Comment by zhaocai** [comment]
# Below are two screenshots to demonstrate

1.`font-size: 24px` : ![Fixed font-size](https://dl.dropboxusercontent.com/u/1897501/Screenshots/ignism-nucleus-dark-ui/fixed%20font-size.PNG)
2.`font-size: 0.9rem` ![Relative font-size](https://dl.dropboxusercontent.com/u/1897501/Screenshots/ignism-nucleus-dark-ui/relative%20font-size.PNG)

The panel-heading is for `atom-script`. Check the icon size on the right side, you can see that the `font-size` is too big.

In fact, using fixed `font-size` assumes the base `font-size` to be the default `14px`. What if some one uses `9px` or `18px` as default, fixed `font-size` would make the theme looks disproportional.

**Comment by ignism** [comment]
thanks! I will implement this in the next patch.

**Comment by zhaocai** [comment]
Thanks. Great Theme!

One more suggestion, the `wrap-guide` looks too distinctive. Try if you like the style below. 

``` less
.wrap-guide {
  background-color: lighten( @base-background-color, 5% );
}
```
