### ISSUE TITLE
Make nucleus work better with custom title bar

### ISSUE THREAD

**Issue by albireox** [ignism/nucleus-dark-ui#70]
The new custom title bar for macOs introduced in atom 1.11.0-beta does not completely integrate with nucleus-dark-ui. Although the effect is not bad, there is a double white line between the tab bar and the title bar, as shown in the screenshot. Maybe nucleus should check if the option is enabled and, if so, remove the white line in the tab bar.

![screen shot 2016-09-02 at 08 41 49](https://cloud.githubusercontent.com/assets/568775/18209892/bc860d94-70ea-11e6-9849-5430ccaa98b5.jpg)

**Comment by ignism** [comment]
Oh definitely! I was so hyped when I read the beta notes. Haven't had time to adjust it, but I will this weekend!

**Comment by ignism** [comment]
pushed patch 0.9.4, while I was at it I removed some more borders to fit the styling better.
