### ISSUE TITLE
Broken Git Diff Color

### ISSUE THREAD

**Issue by calebgrove** [ignism/nucleus-dark-ui#72]
With the latest release of Nucleus there are some problems with the Git diff color.
1. In the file tree, the modified color has been changed to an electric blue (#4fc3f7).
2. In the editor, the modified color is changed to that same blue when the line has the cursor on it:
   ![Gif showing the bug](http://files.grovedesign.co/nucleus-git-bug/nucleus-git-bug.gif)

**Comment by calebgrove** [comment]
Dunno if it helps, but I'm running [Atom Material Syntax](https://atom.io/themes/atom-material-syntax) as the syntax theme.

**Comment by calebgrove** [comment]
Okay, I created a pull request with a fix: https://github.com/ignism/nucleus-dark-ui/pull/73

**Comment by ignism** [comment]
Thanks for the quick fix, patched it to 0.10.2
