### ISSUE TITLE
Update linter styling

### ISSUE THREAD

**Issue by amilajack** [ignism/nucleus-dark-ui#74]
The current theme doesn't seem to match the rest of the UI. I added a more matching UI alternative.

**Current styling:**

<img width="627" alt="screen shot 2016-09-25 at 12 12 15 am" src="https://cloud.githubusercontent.com/assets/6374832/18813611/c083084e-82b4-11e6-8a42-a15ecdf6f7e0.png">
<img width="620" alt="screen shot 2016-09-25 at 12 12 18 am" src="https://cloud.githubusercontent.com/assets/6374832/18813612/c37be386-82b4-11e6-94cb-8d68121bb1de.png">

**Ideal styling (taken from [nova ui](https://github.com/trevordmiller/nova-atom-ui)):**

<img width="621" alt="screen shot 2016-09-25 at 12 07 55 am" src="https://cloud.githubusercontent.com/assets/6374832/18813613/c9f1b268-82b4-11e6-87ae-329b1a910794.png">
<img width="622" alt="screen shot 2016-09-25 at 12 07 58 am" src="https://cloud.githubusercontent.com/assets/6374832/18813614/c9f44014-82b4-11e6-93cf-c73b081d068c.png">

**Comment by ignism** [comment]
I don't see how the linter does not fit the rest of the UI. Actually it's because of the linter coloring, which I really liked, I changed the rest of the overlays. The contrasting lighter color calls for immediate action.
