### ISSUE TITLE
Installed packages font too large?

### ISSUE THREAD

**Issue by albireox** [ignism/nucleus-dark-ui#75]
In general I like the changes in `0.10` (still getting used to the light command palette, though). I have notice, however, that the font size of the installed packages/themes is quite large (see screenshot). Not sure if this is intentional or it happens only to me; maybe it's due to the new relative font-size? It's not a showstopper, but should the font be reduced a tad?

![screen shot 2016-09-25 at 10 02 42](https://cloud.githubusercontent.com/assets/568775/18816902/d13061a2-8307-11e6-84d3-7c9b311c2b2e.png)

**Comment by ignism** [comment]
Definitly! On it.
