### ISSUE TITLE
Ability to change color of the command palette?

### ISSUE THREAD

**Issue by VitaliyR** [ignism/nucleus-dark-ui#76]
Hi there.

In a latest update of the theme the palette became to be light. Is there any option to change it to dark mode as it was before? Maybe some flag in options?

Thanks.

**Comment by severen** [comment]
This bugs me as well, I find the colour change quite jarring.

**Comment by ignism** [comment]
maybe, in the future. However the original issue was refering to the color pre 0.10.11
