### ISSUE TITLE
Command palette deselected text not visible

### ISSUE THREAD

**Issue by adambowles** [ignism/nucleus-dark-ui#78]
The text entered into a command palette disappears when atom window is not active

![screenshot from 2016-09-28 10-00-50](https://cloud.githubusercontent.com/assets/10128574/18907202/97b0888c-8562-11e6-98b0-aaac2eaa50d5.png)
![screenshot from 2016-09-28 10-00-58](https://cloud.githubusercontent.com/assets/10128574/18907203/97b21d8c-8562-11e6-8474-19d2a5f62c2e.png)

**Comment by ignism** [comment]
which command palette is this? Fuzzy Finder?

**Comment by adambowles** [comment]
Yup

**Comment by ignism** [comment]
fixed in 0.10.4

**Comment by adambowles** [comment]
Confirmed fixed
