### ISSUE TITLE
Palette does not play well with git-plus

### ISSUE THREAD

**Issue by albireox** [ignism/nucleus-dark-ui#82]
The new light colour palette does not play very well with git-plus. Colours and buttons are difficult to see. See for example, when trying to use Stage Hunk

<img width="1041" alt="screen shot 2016-10-08 at 18 06 27" src="https://cloud.githubusercontent.com/assets/568775/19216862/47b522a2-8d82-11e6-90d2-8c536d3837ca.png">

This may be related to #81.

**Comment by ignism** [comment]
yeah.. im thinking of rolling back the light overlay. I was really a fan of it, Atom packages not so much though.

**Comment by ignism** [comment]
How does patch 0.10.10 work for you?

**Comment by lironess** [comment]
I had that issue with 0.10.9 too.
I updated to 0.10.10 and it seems better. however, the left column still doesn't look so visible and it's really hard to read it.
![image](https://cloud.githubusercontent.com/assets/4243338/19220421/6edc5fd6-8e35-11e6-8298-8105f4ed7ef6.png)

I'm using atom-dark-fusion-syntax@1.2.4 if it matters.

**Comment by ignism** [comment]
I think 0.10.11 fixed the readability

**Comment by albireox** [comment]
0.10.11 seems to have fixed everything for me, as far as I can see. I like the new palette background colour. It makes text easier to read while still standing a bit apart from the text editor background.
