### ISSUE TITLE
Open config folder button text hitting edge of button

### ISSUE THREAD

**Issue by brianmoran** [ignism/nucleus-dark-ui#84]
Setting padding to 0 for that button in config-menu button-area makes the button more aesthetically pleasing. 

Before:
<img width="200" alt="screen shot 2016-10-27 at 9 27 03 am" src="https://cloud.githubusercontent.com/assets/5261397/19769113/1f173cea-9c28-11e6-9769-9d473c6e74df.png">

After:
<img width="177" alt="screen shot 2016-10-27 at 9 27 22 am" src="https://cloud.githubusercontent.com/assets/5261397/19769115/230990c8-9c28-11e6-9980-a6848131b93e.png">

**Comment by brianmoran** [comment]
PR submitted

**Comment by ignism** [comment]
yep, merged, will upload in new patch. Thanks!

**Comment by brianmoran** [comment]
Np! Great UI!
