### ISSUE TITLE
nucleus-dark-ui with one-dark-syntax lead to some color problem

### ISSUE THREAD

**Issue by ghost** [ignism/nucleus-dark-ui#87]
in the autocomplete-plus tooltips, the parameter's color is hard to recognite.
![problem](https://cloud.githubusercontent.com/assets/17137825/20029184/bfe2dac6-a380-11e6-9da4-3ace4085b6d5.png)

**Comment by ignism** [comment]
What language is this? Or can you help me reproduce this, my parameters are just normal text color.

**Comment by ghost** [comment]
cpp

**Comment by ghost** [comment]
I found this problem with any syntax theme. Not only with one dark syntax theme.

**Comment by ignism** [comment]
I'm having difficulties reproducing it, could you push me in the right direction?

EDIT: forget that, I found it! patching this soon

**Comment by ignism** [comment]
fixed as of 0.10.15

**Comment by ghost** [comment]
It worked like a charm! Thanks!
