### ISSUE TITLE
The tab width becomes small due to too many tabs.

### ISSUE THREAD

**Issue by ghost** [ignism/nucleus-dark-ui#88]
I have too many tabs open at once, and I found the tab width to become very narrow as shown below.
![aa8d6318-1102-4b54-92b9-7022326d46fa](https://cloud.githubusercontent.com/assets/17137825/20088225/a4e6281e-a5b9-11e6-95bb-90e4c71f2f43.png)
Is there any way to control the minimum width?

**Comment by ignism** [comment]
there is a package that creates a second row of tabs, but I have yet to figure out how to make it work with nucleus.
You might be interested in this one though [tree-view-open-files](https://atom.io/packages/tree-view-open-files)

**Comment by ghost** [comment]
Thanks, I'll try it.
