### ISSUE TITLE
Scroll bar

### ISSUE THREAD

**Issue by onetrev** [ignism/nucleus-dark-ui#89]
Pretty sure this just happened with a recent update, but the scroll bar is now old school looking for me.

![image](https://cloud.githubusercontent.com/assets/597601/20546058/f07d898a-b166-11e6-84f2-6a65294260b6.png)

**Comment by scippio** [comment]
Yeah, last update did it

**Comment by joecorkerton** [comment]
Really don't like the new scroll bar, is there a way to revert back to the old one?

**Comment by ignism** [comment]
This must be an issue with the deprecation of the [Shadow DOM](http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html), in preparation for 1.13.0 I removed all `::shadow` and `/deep/` instances. I will try to fix this, although I don't have this issue on OS X. 
For now a quick fix could be to rollback to [0.10.15](https://github.com/ignism/nucleus-dark-ui/releases)

@onetrev Do you run Atom Beta, does it have the same problem in the latest version there?

**Comment by onetrev** [comment]
I don't run Atom Beta, but installed it so I could check for you. And yes, confirmed the scroll bar is back to good/normal in Atom Beta.

**Comment by MichaelAquilina** [comment]
Can confirm this issue shows in the current stable release of Atom and is fixed when using the beta

**Comment by a-tsvil** [comment]
Have same on windows 10. Atom v1.12.5.

**Comment by McAllaster** [comment]
@ignism I am having this issue on OSX El Capitan 10.11.6

Edit: a simple fix right now (as I am using minimap as my scrollbar) is to disable scrollbars inside of the atom-text-editor::shadow element inside of your style.less with the following:

`.vertical-scrollbar, .horizontal-scrollbar, .scrollbar-corner {
    display: none;
  }`

**Comment by ignism** [comment]
I rolled back to a previous commit. just before I removed the shadow dom, which will be standard from version 1.13.0 and higher. But for now I the previous commit will work. Future patches will have a `>= 1.13` in the `engine` section of the `package.json` to avoid further problems.
