### ISSUE TITLE
input text unreadable

### ISSUE THREAD

**Issue by dmaglio** [ignism/nucleus-dark-ui#90]
when i type a text in setting (any input text), the text it's unreadable, i need to select the text to show what i typed.
Same issue in Windows 10 and GNU/Linux (Fedora 25)
![2016-11-23](https://cloud.githubusercontent.com/assets/446573/20556560/0090a932-b168-11e6-9a52-3a4b09011313.png)

![cattura](https://cloud.githubusercontent.com/assets/446573/20556627/4d45adc2-b168-11e6-8913-14d9ca9ad981.png)

**Comment by ignism** [comment]
I am unable to fix this atm, but will look into it as soon as possible. For now a quick fix could be to try a different syntax-theme.

**Comment by dmaglio** [comment]
thanks, this theme with solarized dark was very very nice 😢

**Comment by ignism** [comment]
I patched it, let me know if this is back to normal for you.

**Comment by dmaglio** [comment]
thanks, now it's fixed and the result is beautiful 😄
