### ISSUE TITLE
New releases

### ISSUE THREAD

**Issue by Jarvvski** [ignism/nucleus-dark-ui#91]
Please stop making new releases for changes of 5 lines.

Unless it's breaking Atom, I really don't see why we need 3 updates within the span of 3 days.

Just make it a weekly thing at max.

Thanks.

**Comment by ignism** [comment]
When I tackle an issue, I'd like to patch it right away.

**Comment by edwinksl** [comment]
@Jarvvski Does it really bother you that much to update Atom packages? It is a simple point-and-click maneuver followed by restarting the editor. This only takes seconds and you get the benefit of bugs being fixed.

**Comment by Jarvvski** [comment]
yes @edwinksl I'd rather not have to keep updating the same exact plugin every day.

If it's a blocker, then why on earth was it released in the first place.

If it's a hotfix, then why can't it wait until the end of the week?
