### ISSUE TITLE
Panel not popping up when used with latextools package

### ISSUE THREAD

**Issue by edwinksl** [ignism/nucleus-dark-ui#92]
I use the `atom-latextools` package at https://github.com/msiniscalchi/atom-latextools for writing LaTeX and the package provides a feature where typing `\ref` or `\cite` would result in a panel to pop up that is populated with references and BibTeX entries respectively. This feature is documented at https://github.com/msiniscalchi/atom-latextools/blob/master/MANUAL.md#details. Unfortunately, I can't see the panel when using the Nucleus Dark UI but I can see it if I use other UIs such as the One Dark UI.

**Comment by ignism** [comment]
I am trying to duplicate this, but I am unfamiliar with LaTeX. Besides the tools package is there anything else I need to install?

Or could you give me exact steps how to reproduce your problem?

**Comment by edhv** [comment]
bump @edwinksl

**Comment by edwinksl** [comment]
@ignism @edhv Oops, sorry, was busy the past week.

Here is a minimal example to recreate the problem. First, install the `language-latex` (https://atom.io/packages/language-latex) and `latextools` (https://atom.io/packages/latextools) packages. Second, create an empty file called `test.bib`. Third, create a file named `test.tex` that contains:

```
\documentclass{report}

\begin{document}

\bibliography{test}
\end{document}
```

Now, type `\cite{` on a new line right after `\begin{document}` and a panel should pop up that contains a single entry called `???? -()` (only question marks and parentheses because `test.bib` is empty). This works in the One Dark UI for example but does not work in the Nucleus Dark UI.

**Comment by edwinksl** [comment]
That's some insanely quick bug fix. Thanks!
