### ISSUE TITLE
Highlights always set to a font size of 13px

### ISSUE THREAD

**Issue by TheEnigmaBlade** [ignism/nucleus-dark-ui#93]
The font size of `.highlight` is always set to a 13px, even when the editor is set otherwise.

The `.highlight-type` mixin includes the `.text(normal)` mixin, which sets `font-size` to the constant `@font-size` set to 13px.

A potential solution, which works for the singular use case I've tested, is to stop setting `font-size` for `.highlight`. It should inherit the appropriate font size.

Here are some examples with the pigments package:

![](http://i.imgur.com/MF92ujv.png)

![](http://i.imgur.com/KDiLPkM.png)

![](http://i.imgur.com/fdMkmni.png)

**Comment by ignism** [comment]
Thanks for the detective work, will implement this in next patch!
