### ISSUE TITLE
Fonts are all quite large

### ISSUE THREAD

**Issue by kaicataldo** [ignism/nucleus-dark-ui#95]
Thanks for this theme - it's beautiful! I'm just trying out Atom again and reinstalled Nucleus Dark and am noticing that all the type (tree, tabs, settings) is really large. Is this intentional? If so, any recommendations as to how I scale it all down? Thanks in advance :)

**Comment by ignism** [comment]
I noticed this also when changing themes, for now have you tried restarting?

**Comment by kaicataldo** [comment]
Not seeing a difference when I do a window reload or when I quit and restart Atom. Does that fix it for you? Should have mentioned - I'm on OSX v10.11.6 with Atom v1.12.7.

**Comment by ignism** [comment]
I'm not sure whether this is a problem with nucleus. Could you do me a favor and inspect the fonts that are larg and see what sets them to that size?

**Comment by mikeerickson** [comment]
@kaicataldo Did this ever get resolved?  I came here with the same questions.   My fonts are quite large in things like the Command-Palette, Settings View, etc.    

I am comparing to my previous theme `Seti Classic`

![image](https://cloud.githubusercontent.com/assets/183153/22408884/a1f42fb8-e635-11e6-8af3-1bb46da1794e.png)

![image](https://cloud.githubusercontent.com/assets/183153/22408886/ad72ed20-e635-11e6-865d-dfdf7949d3c1.png)

![image](https://cloud.githubusercontent.com/assets/183153/22408892/bce98b24-e635-11e6-9c85-f601683dfcd2.png)

![image](https://cloud.githubusercontent.com/assets/183153/22408900/d33fcd84-e635-11e6-89b7-f5d749fd3e2e.png)

**Comment by ignism** [comment]
Working as intended.
