### ISSUE TITLE
Deprecated selector in `nucleus-dark-ui/index.less`

### ISSUE THREAD

**Issue by carlrosell** [ignism/nucleus-dark-ui#96]
In `nucleus-dark-ui/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor .wrap-guide,
atom-text-editor::shadow .wrap-guide,
:host .wrap-guide` => `atom-text-editor .wrap-guide,
atom-text-editor.editor .wrap-guide,
:host .wrap-guide`

* `atom-text-editor .indent-guide,
atom-text-editor::shadow .indent-guide,
:host .indent-guide` => `atom-text-editor .indent-guide,
atom-text-editor.editor .indent-guide,
:host .indent-guide`

* `atom-text-editor .bracket-matcher .region,
atom-text-editor::shadow .bracket-matcher .region,
:host .bracket-matcher .region` => `atom-text-editor .bracket-matcher .region,
atom-text-editor.editor .bracket-matcher .region,
:host .bracket-matcher .region`

* `atom-text-editor .invisible-character,
atom-text-editor::shadow .invisible-character,
:host .invisible-character` => `atom-text-editor .invisible-character,
atom-text-editor.editor .invisible-character,
:host .invisible-character`

* `atom-text-editor .invisible,
atom-text-editor::shadow .invisible,
:host .invisible` => `atom-text-editor .invisible,
atom-text-editor.editor .invisible,
:host .invisible`

* `atom-text-editor .line.cursor-line,
atom-text-editor::shadow .line.cursor-line,
:host .line.cursor-line` => `atom-text-editor .line.cursor-line,
atom-text-editor.editor .line.cursor-line,
:host .line.cursor-line`

* `atom-text-editor .selection .region,
atom-text-editor::shadow .selection .region,
:host .selection .region` => `atom-text-editor .selection .region,
atom-text-editor.editor .selection .region,
:host .selection .region`

* `atom-text-editor .line-number,
atom-text-editor::shadow .line-number,
:host .line-number` => `atom-text-editor .line-number,
atom-text-editor.editor .line-number,
:host .line-number`

* `atom-text-editor .line-number.cursor-line,
atom-text-editor::shadow .line-number.cursor-line,
:host .line-number.cursor-line` => `atom-text-editor .line-number.cursor-line,
atom-text-editor.editor .line-number.cursor-line,
:host .line-number.cursor-line`

* `atom-text-editor .line-number.cursor-line-no-selection,
atom-text-editor::shadow .line-number.cursor-line-no-selection,
:host .line-number.cursor-line-no-selection` => `atom-text-editor .line-number.cursor-line-no-selection,
atom-text-editor.editor .line-number.cursor-line-no-selection,
:host .line-number.cursor-line-no-selection`

* `atom-text-editor .line-number.git-line-added,
atom-text-editor::shadow .line-number.git-line-added,
:host .line-number.git-line-added` => `atom-text-editor .line-number.git-line-added,
atom-text-editor.editor .line-number.git-line-added,
:host .line-number.git-line-added`

* `atom-text-editor .line-number.git-line-added.cursor-line,
atom-text-editor::shadow .line-number.git-line-added.cursor-line,
:host .line-number.git-line-added.cursor-line,
atom-text-editor .line-number.git-line-added.cursor-line-no-selection,
atom-text-editor::shadow .line-number.git-line-added.cursor-line-no-selection,
:host .line-number.git-line-added.cursor-line-no-selection` => `atom-text-editor .line-number.git-line-added.cursor-line,
atom-text-editor.editor .line-number.git-line-added.cursor-line,
:host .line-number.git-line-added.cursor-line,
atom-text-editor .line-number.git-line-added.cursor-line-no-selection,
atom-text-editor.editor .line-number.git-line-added.cursor-line-no-selection,
:host .line-number.git-line-added.cursor-line-no-selection`

* `atom-text-editor .line-number.git-line-modified,
atom-text-editor::shadow .line-number.git-line-modified,
:host .line-number.git-line-modified` => `atom-text-editor .line-number.git-line-modified,
atom-text-editor.editor .line-number.git-line-modified,
:host .line-number.git-line-modified`

* `atom-text-editor .line-number.git-line-modified.cursor-line,
atom-text-editor::shadow .line-number.git-line-modified.cursor-line,
:host .line-number.git-line-modified.cursor-line,
atom-text-editor .line-number.git-line-modified.cursor-line-no-selection,
atom-text-editor::shadow .line-number.git-line-modified.cursor-line-no-selection,
:host .line-number.git-line-modified.cursor-line-no-selection` => `atom-text-editor .line-number.git-line-modified.cursor-line,
atom-text-editor.editor .line-number.git-line-modified.cursor-line,
:host .line-number.git-line-modified.cursor-line,
atom-text-editor .line-number.git-line-modified.cursor-line-no-selection,
atom-text-editor.editor .line-number.git-line-modified.cursor-line-no-selection,
:host .line-number.git-line-modified.cursor-line-no-selection`

* `atom-text-editor .line-number.git-line-removed,
atom-text-editor::shadow .line-number.git-line-removed,
:host .line-number.git-line-removed` => `atom-text-editor .line-number.git-line-removed,
atom-text-editor.editor .line-number.git-line-removed,
:host .line-number.git-line-removed`

* `atom-text-editor .line-number.git-line-removed.cursor-line,
atom-text-editor::shadow .line-number.git-line-removed.cursor-line,
:host .line-number.git-line-removed.cursor-line,
atom-text-editor .line-number.git-line-removed.cursor-line-no-selection,
atom-text-editor::shadow .line-number.git-line-removed.cursor-line-no-selection,
:host .line-number.git-line-removed.cursor-line-no-selection` => `atom-text-editor .line-number.git-line-removed.cursor-line,
atom-text-editor.editor .line-number.git-line-removed.cursor-line,
:host .line-number.git-line-removed.cursor-line,
atom-text-editor .line-number.git-line-removed.cursor-line-no-selection,
atom-text-editor.editor .line-number.git-line-removed.cursor-line-no-selection,
:host .line-number.git-line-removed.cursor-line-no-selection`

* `atom-text-editor .gutter,
atom-text-editor::shadow .gutter,
:host .gutter` => `atom-text-editor .gutter,
atom-text-editor.editor .gutter,
:host .gutter`

* `atom-text-editor .gutter .line-number.folded,
atom-text-editor::shadow .gutter .line-number.folded,
:host .gutter .line-number.folded,
atom-text-editor .gutter .line-number.folded .icon-right,
atom-text-editor::shadow .gutter .line-number.folded .icon-right,
:host .gutter .line-number.folded .icon-right,
atom-text-editor .gutter .line-number:after,
atom-text-editor::shadow .gutter .line-number:after,
:host .gutter .line-number:after` => `atom-text-editor .gutter .line-number.folded,
atom-text-editor.editor .gutter .line-number.folded,
:host .gutter .line-number.folded,
atom-text-editor .gutter .line-number.folded .icon-right,
atom-text-editor.editor .gutter .line-number.folded .icon-right,
:host .gutter .line-number.folded .icon-right,
atom-text-editor .gutter .line-number:after,
atom-text-editor.editor .gutter .line-number:after,
:host .gutter .line-number:after`

* `atom-text-editor .gutter .line-number.folded.cursor-line,
atom-text-editor::shadow .gutter .line-number.folded.cursor-line,
:host .gutter .line-number.folded.cursor-line,
atom-text-editor .gutter .line-number.folded.cursor-line-no-selection,
atom-text-editor::shadow .gutter .line-number.folded.cursor-line-no-selection,
:host .gutter .line-number.folded.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.folded.cursor-line,
atom-text-editor.editor .gutter .line-number.folded.cursor-line,
:host .gutter .line-number.folded.cursor-line,
atom-text-editor .gutter .line-number.folded.cursor-line-no-selection,
atom-text-editor.editor .gutter .line-number.folded.cursor-line-no-selection,
:host .gutter .line-number.folded.cursor-line-no-selection`

* `atom-text-editor .gutter .line-number.folded.cursor-line .icon-right,
atom-text-editor::shadow .gutter .line-number.folded.cursor-line .icon-right,
:host .gutter .line-number.folded.cursor-line .icon-right,
atom-text-editor .gutter .line-number.folded.cursor-line-no-selection .icon-right,
atom-text-editor::shadow .gutter .line-number.folded.cursor-line-no-selection .icon-right,
:host .gutter .line-number.folded.cursor-line-no-selection .icon-right` => `atom-text-editor .gutter .line-number.folded.cursor-line .icon-right,
atom-text-editor.editor .gutter .line-number.folded.cursor-line .icon-right,
:host .gutter .line-number.folded.cursor-line .icon-right,
atom-text-editor .gutter .line-number.folded.cursor-line-no-selection .icon-right,
atom-text-editor.editor .gutter .line-number.folded.cursor-line-no-selection .icon-right,
:host .gutter .line-number.folded.cursor-line-no-selection .icon-right`

* `atom-text-editor .fold-marker:after,
atom-text-editor::shadow .fold-marker:after,
:host .fold-marker:after` => `atom-text-editor .fold-marker:after,
atom-text-editor.editor .fold-marker:after,
:host .fold-marker:after`

* `atom-text-editor.mini,
atom-text-editor.mini::shadow` => `atom-text-editor.mini,
atom-text-editor.mini.editor`

* `atom-text-editor.mini .cursor,
atom-text-editor.mini::shadow .cursor` => `atom-text-editor.mini .cursor,
atom-text-editor.mini.editor .cursor`

* `atom-text-editor.mini .text,
atom-text-editor.mini::shadow .text,
atom-text-editor.mini .regexp,
atom-text-editor.mini::shadow .regexp` => `atom-text-editor.mini .text,
atom-text-editor.mini.editor .syntax--text,
atom-text-editor.mini .regexp,
atom-text-editor.mini.editor .syntax--regexp`

* `atom-text-editor.mini.is-focused,
atom-text-editor.mini.is-focused::shadow,
atom-text-editor.mini:hover,
atom-text-editor.mini:hover::shadow` => `atom-text-editor.mini.is-focused,
atom-text-editor.mini.is-focused.editor,
atom-text-editor.mini:hover,
atom-text-editor.mini:hover.editor`

* `atom-text-editor.mini.is-focused .text,
atom-text-editor.mini.is-focused::shadow .text,
atom-text-editor.mini:hover .text,
atom-text-editor.mini:hover::shadow .text,
atom-text-editor.mini.is-focused .regexp,
atom-text-editor.mini.is-focused::shadow .regexp,
atom-text-editor.mini:hover .regexp,
atom-text-editor.mini:hover::shadow .regexp` => `atom-text-editor.mini.is-focused .text,
atom-text-editor.mini.is-focused.editor .syntax--text,
atom-text-editor.mini:hover .text,
atom-text-editor.mini:hover.editor .syntax--text,
atom-text-editor.mini.is-focused .regexp,
atom-text-editor.mini.is-focused.editor .syntax--regexp,
atom-text-editor.mini:hover .regexp,
atom-text-editor.mini:hover.editor .syntax--regexp`

* `.overlay atom-text-editor.mini,
atom-panel.modal atom-text-editor.mini,
.overlay atom-text-editor.mini::shadow,
atom-panel.modal atom-text-editor.mini::shadow` => `.overlay atom-text-editor.mini,
atom-panel.modal atom-text-editor.mini,
.overlay atom-text-editor.mini.editor,
atom-panel.modal atom-text-editor.mini.editor`

* `.overlay atom-text-editor.mini .text,
atom-panel.modal atom-text-editor.mini .text,
.overlay atom-text-editor.mini::shadow .text,
atom-panel.modal atom-text-editor.mini::shadow .text` => `.overlay atom-text-editor.mini .text,
atom-panel.modal atom-text-editor.mini .text,
.overlay atom-text-editor.mini.editor .syntax--text,
atom-panel.modal atom-text-editor.mini.editor .syntax--text`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by sirschuyler** [comment]
thanks @tbremer can this be merged into master?
