### ISSUE TITLE
Fuzzy Matches Not Highlighted

### ISSUE THREAD

**Issue by mikeerickson** [ignism/nucleus-dark-ui#99]
In addition to size issues, I have noticed that this UI does not show fuzzy matches in Command Palette (compare the following screenshots, darker one is Seti Classic)

![image](https://cloud.githubusercontent.com/assets/183153/22408920/0bc88eb6-e636-11e6-8425-25724eaa6b1f.png)

![image](https://cloud.githubusercontent.com/assets/183153/22408922/1a0419f0-e636-11e6-8938-11491d0dcd54.png)

**Comment by ignism** [comment]
That is indeed something I removed on purpose. I think it looks cleaner and quieter without.
